# -*- coding: utf-8 -*-
"""practicee

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naMi_VsFgLeDtrn6dlaHxZ-UtrgqJbHW
"""

# Write a for loop to calculate the factorial of a number provided by the user.
n=int(input())
factorial=1
for i in range(1,n+1):
  factorial*=i
print(factorial)

# program to find the first duplicate value in a list
a = [2, 3, 4, 5, 2, 6, 4]

b = set()
for i in a:
    if i in b:
        print("First duplicate:", i)
        break
    b.add(i)
else:
    print("No duplicates found")

# Write a while loop that asks the user to enter a number and stops when the number is 0.
n=None
while n!=0:
  n=int(input())
  if n==0:4
    print(f'{n}')

n=None
sum=0
while n!=0:
  n=int(input())
  sum+=n
print(sum)

# Write a for loop to iterate over a list of strings and print each string in uppercase.
a=['hello','shhs','abc']
for i in a:
  print(i.upper())

# Write a while loop to reverse a number provided by the user.
a=int(input())
rev=0
temp=a
while a>0:
  rev=rev*10+a%10
  a=a//10
print(rev)

# # Provide an example where you use a for loop inside a while loop.
# a=123
# while a!=0:
#  for i in range(1, a + 1):
#         if i % 2 == 0:  # Check if the number is even
#             print(i) :

# Write a for loop to print the Fibonacci sequence up to n terms, where n is provided by the user.
n=int(input())
a,b=0,1
print(a,b)
 c=a+b
 print(c)
a,b=b,c

# Write a for loop that iterates over a dictionary and prints the key-value pairs in the format key:value.
a={'name':'abc','class':'bca','roll no':321}
for key,value in a.items():
  print(key,value)

# Write a while loop to sum the digits of a positive integer provided by the user.
a=int(input())
sum=0
rev=0
while a>0:
  rem=a%10
  a=a//10
  sum+=rem
print(sum)

# Write a for loop to print all prime numbers between 2 and 50.
for i in range(2,51):
  for j in range(2,i):
    if i%j==0:
      break
  else:
      print(i)

# Write a for loop to reverse a string provided by the user without using built-in functions.
a='hello'
rev=''
for char in a:
  rev=char+rev
print(rev)

# reverse using .join
a='hello'
b=''.join(reversed(a))
print(b)

#reverse using slicing
a='hello'
b=a[::-1]
print(b)

# Given a list of words, write a for loop to find the longest word and its length.